### ISSUE TITLE
Build Front End

### ISSUE THREAD

**Issue by wagonhelm** [wagonhelm/neuro-car#7]

**Comment by wagonhelm** [comment]
Two Eyes - Most Important -> Open, Closed
                   Secondary Cool -> Up, Down, Lefft Right

Fatigue Scale - Emojis, Smiling, Neutral, Frowning 

Optional:
Road emoji if focus is on the road

**Comment by giancarlopernudisegura** [comment]
I'm also working on getting the server up and working.

**Comment by giancarlopernudisegura** [comment]
Finished everything specified.
